### ISSUE TITLE
error setting user personal information

### ISSUE THREAD

**Issue by rileydog** [collective/demo.plone.de#23] opened 2017-12-16 00:33 UTC
when on http://demo.plone.de
=========
and i select from l/h toolbar: manager/preferences/personal information I get this error:

(where do I file bug reports for 5.1)
Traceback (innermost last):
Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module plone.app.users.browser.userdatapanel, line 93, in call
Module z3c.form.form, line 233, in call
Module plone.z3cform.fieldsets.extensible, line 65, in update
Module plone.z3cform.patch, line 30, in GroupForm_update
Module z3c.form.group, line 132, in update
Module z3c.form.form, line 136, in updateWidgets
Module z3c.form.field, line 243, in update
Module z3c.form.datamanager, line 102, in canWrite
Module z3c.form.datamanager, line 66, in adapted_context
TypeError: (‘Could not adapt’, <Container at /Plone/en>, )

**Comment by pbauer** [comment] 2017-12-16 06:40
This is a duplicate of https://github.com/plone/Products.CMFPlone/issues/2116

**Closed by pbauer** 2017-12-16 06:40 UTC
